name: Debug GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode'
        required: false
        default: 'full'

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Environment Check
      run: |
        echo "=== 環境情報 ==="
        echo "Runner: $(whoami)"
        echo "PWD: $(pwd)"
        echo "Date: $(date)"
        echo ""
        
    - name: Raw Environment Variables
      run: |
        echo "=== 生の環境変数 ==="
        env | grep -E "^WORDPRESS_|^GITHUB_" || echo "該当する環境変数なし"
        echo ""
        
    - name: Secret Length Test
      env:
        WP_URL: ${{ secrets.WORDPRESS_URL }}
        WP_USER: ${{ secrets.WORDPRESS_USERNAME }}
        WP_PASS: ${{ secrets.WORDPRESS_APP_PASSWORD }}
      run: |
        echo "=== Secret長さテスト ==="
        echo "WORDPRESS_URL length: ${#WP_URL}"
        echo "WORDPRESS_USERNAME length: ${#WP_USER}"
        echo "WORDPRESS_APP_PASSWORD length: ${#WP_PASS}"
        echo ""
        
    - name: Secret Content Test (Safe)
      env:
        WP_URL: ${{ secrets.WORDPRESS_URL }}
        WP_USER: ${{ secrets.WORDPRESS_USERNAME }}
        WP_PASS: ${{ secrets.WORDPRESS_APP_PASSWORD }}
      run: |
        echo "=== Secret内容テスト（安全） ==="
        
        if [ -n "$WP_URL" ]; then
          echo "✅ WORDPRESS_URL: 設定済み"
          echo "   先頭3文字: ${WP_URL:0:3}"
          echo "   末尾3文字: ${WP_URL: -3}"
        else
          echo "❌ WORDPRESS_URL: 空"
        fi
        
        if [ -n "$WP_USER" ]; then
          echo "✅ WORDPRESS_USERNAME: 設定済み"
          echo "   先頭3文字: ${WP_USER:0:3}"
        else
          echo "❌ WORDPRESS_USERNAME: 空"
        fi
        
        if [ -n "$WP_PASS" ]; then
          echo "✅ WORDPRESS_APP_PASSWORD: 設定済み"
          echo "   先頭3文字: ${WP_PASS:0:3}"
        else
          echo "❌ WORDPRESS_APP_PASSWORD: 空"
        fi
        echo ""
        
    - name: Alternative Secret Access
      run: |
        echo "=== 代替Secret取得方法 ==="
        
        # GitHub APIを使用してSecret存在確認（値は取得できないが存在確認は可能）
        echo "GitHub API経由でのSecret存在確認:"
        
        # 環境変数の直接確認
        echo "環境変数の直接確認:"
        printenv | grep -i wordpress || echo "WordPress関連の環境変数なし"
