name: Test GitHub Secrets

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test WordPress Secrets
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
      run: |
        echo "=== GitHub Secrets確認 ==="
        
        if [ -z "$WORDPRESS_URL" ]; then
          echo "❌ WORDPRESS_URL が設定されていません"
        else
          echo "✅ WORDPRESS_URL: 設定済み (${#WORDPRESS_URL}文字)"
        fi
        
        if [ -z "$WORDPRESS_USERNAME" ]; then
          echo "❌ WORDPRESS_USERNAME が設定されていません"
        else
          echo "✅ WORDPRESS_USERNAME: 設定済み (${#WORDPRESS_USERNAME}文字)"
        fi
        
        if [ -z "$WORDPRESS_APP_PASSWORD" ]; then
          echo "❌ WORDPRESS_APP_PASSWORD が設定されていません"
        else
          echo "✅ WORDPRESS_APP_PASSWORD: 設定済み (${#WORDPRESS_APP_PASSWORD}文字)"
        fi
        
        echo ""
        echo "=== WordPress REST API接続テスト ==="
        
        if [ -n "$WORDPRESS_USERNAME" ] && [ -n "$WORDPRESS_APP_PASSWORD" ]; then
          curl -s -u "$WORDPRESS_USERNAME:$WORDPRESS_APP_PASSWORD" \
            "$WORDPRESS_URL/wp-json/wp/v2/users/me" | head -c 200
          echo ""
          echo "接続テスト完了"
        else
          echo "認証情報が不足しているため接続テストをスキップ"
        fi
