        # 投稿データ作成（tagsを削除してシンプルに）
        post_data = {
            'title': f'開発作業完了報告 - {datetime.now().strftime("%Y/%m/%d")}',
            'content': content.replace('\n', '<br>\n'),
            'status': 'draft',  # 下書き保存
            'categories': [1]   # 開発ログカテゴリ（デフォルトカテゴリ）
        }
